name: Test

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-node@v4.0.2
        with:
          node-version: 22
      - name: Install
        run: npm ci
      - name: fs glob
        run: node ./fs-glob.mjs
      - name: node glob
        run: node ./node-glob.mjs
      - name: fast glob
        run: node ./fast-glob.mjs

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
